#!/bin/sh

NAME=puppy-bootstrap
PIDFILE=/var/run/$NAME.pid

start() {
    echo "Starting $NAME..."
    start-stop-daemon -S -b -m -p $PIDFILE -c player -x /bin/sh -- -l -c 'export HOME=/home/player USER=player LOGNAME=player; exec /usr/local/bin/puppy-bootstrap.sh'
}

stop() {
    echo "Stopping $NAME..."
    start-stop-daemon -K -p $PIDFILE
    rm -f $PIDFILE
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
