KEY_VOLUMEUP+BTN_MODE           1    /usr/local/bin/brightstep.sh up
KEY_VOLUMEDOWN+BTN_MODE         1    /usr/local/bin/brightstep.sh down
BTN_MODE+BTN_START+BTN_SELECT   1    /usr/local/bin/kill-active-process.sh
BTN_START+BTN_MODE+BTN_SELECT   1    /usr/local/bin/kill-active-process.sh
BTN_SELECT+BTN_MODE+BTN_START   1    /usr/local/bin/kill-active-process.sh
