[settings]
; fps_limit     = 60             ; 0 = unlimited (vsync only). 30 saves battery.
vsync           = 0
; adaptive      = 1              ; auto-reduce star count if frame rate drops
particles       = 1000              ; override star count of the preset (max 1000)
font            = /usr/share/fonts/Inter_24pt-Medium.ttf

[credits]
goodluckOS = is brought to you by...
JEREMY CLARK  = PROJECT LEAD/ENGINEERING/DEVELOPMENT
MAICON ALVES  = ENGINEERING/DEVELOPMENT
MUHAMMED BAYRAK = A23 TESTING/DEVELOPMENT
MORTELIL = ENGINEERING
JEFERSON LOPES = DEVELOPMENT
LCDYK0517 = TESTING
LESS-HUCKLEBERRY-628 = REVERSE-ENGINEERING
ESISLA = TESTING/DEBUGGING
KristofferAlvinDahlgren = TESTING
CYRENOC = TESTING
Old4444 = TESTING
AranhaRush = TESTING
ANONYMOUS $3 DONOR = FUNDING
YOU = BETA TESTING
THANK YOU
